### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by andrewpbray** [qmd-lab/quarto-course-website#2]
@ryanlovett @paciorek If you have some time, would you mind testing out the functionality of this site machinery?

I think I've got the main features that I was hoping for implemented, namely:

1. schedule that uses CSS grid and looks good on mobile
2. partial rendering (either manually toggling or doing it by date)
3. a "this week" bit at the top of the homepage.
4. adaptive navigation: document listings and sidebar navigation that updates to any partial render.

This is done via .ts scripts, so there shouldn't be any additional dependencies beyond quarto. There is one last niggling issue: I'd like to be able to stash everything that I can inside an `assets` subdir to clean up the home dir. That's the subject of the other open issue here.

My thought was that this could be a general course website for any department / discipline at any institution. Happy to work to be sure it's compatible with what you've developed for stat in particular.

**Comment by paciorek** [comment]
I've been experimenting the last week with a branch in our stat999-quarto repo to have some of this functionality in our template. I'll take a look at where you currently stand to make sure I pick up your recent changes.
