### ISSUE TITLE
question about thresholdDate

### ISSUE THREAD

**Issue by paciorek** [qmd-lab/quarto-course-website#5]
It looks like you are picking up the thresholdDate from a value hard-coded in `_config.yml`, but presumably one would want this to be done by querying the actual date on which the action is run.

I'm actually not following how you do this for real in Stat 20. It looks like you are doing it by modifying values of `render` in `_config.yml` manually, but I thought you wanted this all to be automated...

**Comment by andrewpbray** [comment]
Indeed, that's a first-step thing: get it working on a fixed date string, then be able to build the date string using system time. That's been on the back burner while I've been working on a few other things, but i should get there soon. I'll open up a distinct issue for that feature to be sure it happens.
